In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [5]:
dataset1=pd.read_csv('dataset1.csv')

In [9]:
from sklearn.preprocessing import LabelEncoder
for i in range(len(dataset1.columns)):
    typ=type(dataset1.iloc[1,i])
    #if(typ==str):
    print(typ)    

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>


In [11]:
dataset1.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1', 'Sr.No.',
       'Cut Off Merit (Score)', 'Choice Code', 'Institute', 'Course Name',
       'Exam (JEE/MHT- CET)', 'Type', 'Seat Type', 'score'],
      dtype='object')

In [12]:
x=dataset1[['score','Type','Seat Type','Exam (JEE/MHT- CET)']]

In [23]:
x.columns

Index(['score', 'Type', 'Seat Type', 'Exam (JEE/MHT- CET)'], dtype='object')

In [16]:
for i in range(len(x.columns)):
    typ=type(x.iloc[1,i])
    if(typ==str):
        x.iloc[:,i]=LabelEncoder().fit_transform(x.iloc[:,i])

c:\users\vaidehi jirafe\appdata\local\programs\python\python37\lib\site-packages\pandas\core\indexing.py:965: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s


In [17]:
x

score  Type  Seat Type  Exam (JEE/MHT- CET)
0       207     0          0                    1
1       191     0          0                    1
2       187     0          0                    1
3       182     0          0                    1
4       175     0          0                    1
...     ...   ...        ...                  ...
1112     39     0          0                    0
1113     39     1          2                    0
1114     39     0          0                    0
1115     39     0          0                    0
1116     38     2         30                    0

[1117 rows x 4 columns]

In [29]:
from sklearn.neighbors import NearestNeighbors

In [30]:
model_knn=NearestNeighbors(metric='cosine',algorithm='brute').fit(x)

In [31]:
x.iloc[110]

score                  80
Type                    0
Seat Type               0
Exam (JEE/MHT- CET)     1
Name: 110, dtype: int64

In [33]:
model_knn

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

    distance,indices=model_knn.k

In [34]:
distance,indices=model_knn.kneighbors(x.iloc[11].values.reshape(1,-1),n_neighbors=15)

In [35]:
distance

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 9.25456334e-09,
        1.66786958e-08, 3.28702986e-08, 7.05261128e-08, 1.41339440e-07,
        1.41339440e-07, 1.61927439e-07, 2.00074002e-07, 2.74321216e-07,
        3.07549746e-07, 3.16792168e-07, 3.16792168e-07]])

In [36]:
indices

array([[12, 11, 13, 14, 15, 10, 16,  8,  9,  7, 17, 18,  6, 19, 20]],
      dtype=int64)

In [39]:
y=dataset1['Course Name']
z=dataset1['Institute']

In [51]:
dic={}
k=pd.DataFrame()
for i in range(len(indices.flatten())):
    dic=(y[indices.flatten()[i]],z[indices.flatten()[i]],distance.flatten()[i])
    print(dic)
    

('Electronics and Telecommunication\nEngg', "3215 - Bhartiya Vidya Bhavan's Sardar Patel Institute  of Technology , Andheri, Mumbai", 0.0)
('Computer Engineering', "6273 - Bansilal Ramnath Agarawal Charitable Trust's Vishwakarma Institute of\nTechnology, Bibwewadi, Pune", 0.0)
('Computer Engineering', '3181 - K.J.Somaiya College of Engineering, Vidyavihar, Mumbai', 0.0)
('Information Technology', "6273 - Bansilal Ramnath Agarawal Charitable Trust's Vishwakarma Institute of\nTechnology, Bibwewadi, Pune", 9.254563337890431e-09)
('Surface Coating Technology', '3036 - Institute of Chemical Technology, Matunga, Mumbai', 1.667869575783243e-08)
('Information Technology', "3199 - Shri Vile Parle Kelvani Mandal's Dwarkadas J. Sanghvi College of Engineering,\nVile Parle,Mumbai", 3.287029859411206e-08)
('Computer Science and Engineering', '4115 - Shri Ramdeobaba College of Engineering and Management, Nagpur', 7.052611283864252e-08)
('Computer Engineering', "3199 - Shri Vile Parle Kelvani Mandal's

In [52]:
y[11]

'Computer Engineering'

In [53]:
dic

('Information Technology',
 '3181 - K.J.Somaiya College of Engineering, Vidyavihar, Mumbai',
 3.1679216805358124e-07)

In [64]:
sa=np.sort(distance[0])

In [69]:
sa=(distance,indices)

In [70]:
sa

(array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 9.25456334e-09,
         1.66786958e-08, 3.28702986e-08, 7.05261128e-08, 1.41339440e-07,
         1.41339440e-07, 1.61927439e-07, 2.00074002e-07, 2.74321216e-07,
         3.07549746e-07, 3.16792168e-07, 3.16792168e-07]]),
 array([[12, 11, 13, 14, 15, 10, 16,  8,  9,  7, 17, 18,  6, 19, 20]],
       dtype=int64))